Sorting: Sorting.cpp
	g++ -g -Wall -o Sorting Sorting.o

Sorting.cpp:
	g++ -c -Wall -g src/Sorting.cpp Sorting.o

# the compiler: gcc for C program, define as g++ for C++
 # CC = g++
 
  # compiler flags:
  #  -g     - this flag adds debugging information to the executable file
  #  -Wall  - this flag is used to turn on most compiler warnings
  #CFLAGS  = -g -Wall
 
  # The build target 
  #TARGET = Sorting.cpp
 
#  all: $(TARGET)
 
#  $(TARGET): $(TARGET).c
 #             $(CC) $(CFLAGS) -o $(TARGET) $(TARGET).c
 
  #clean:
   #           $(RM) $(TARGET)